name: DemoApp CI

on:
  push:
    branches: [ cicd ]
  pull_request:
    branches: [ cicd ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest

      - name: Check code formatting
        run: |
          pip install black
          black --check .

      - name: Build (example)
        run: |
          echo "Build step goes here"

      - name: Notify on success
        if: success()
        run: echo "🎉 Build and tests passed!"